export type Product = {
  id: string;
  name: string;
  slug: string;
  category: string;
  gender: 'Women' | 'Men' | 'Accessories';
  price: number;
  compareAt?: number;
  description: string;
  colors: string[];
  sizes: string[];
  image: string;
  imageAlt: string;
  featured?: boolean;
  newArrival?: boolean;
  materials: string;
  sku: string;
};

const img = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=900&q=85`;

export const products: Product[] = [
  {id:'p1',name:'Sculpted Wool Coat',slug:'sculpted-wool-coat',category:'Outerwear',gender:'Women',price:420,compareAt:540,description:'A considered silhouette in warm double-faced wool, cut for a softly structured line.',colors:['Oat','Black'],sizes:['XS','S','M','L'],image:img('photo-1539109136881-3be0616acf4b'),imageAlt:'Model wearing sculpted wool coat',featured:true,newArrival:true,materials:'90% wool, 10% cashmere',sku:'VE-OW-001'},
  {id:'p2',name:'Column Satin Dress',slug:'column-satin-dress',category:'Dresses',gender:'Women',price:295,description:'Fluid satin falls from a clean neckline into a long, elegant column.',colors:['Noir','Pearl'],sizes:['XS','S','M','L'],image:img('photo-1515886657613-9f3515b0c78f'),imageAlt:'Woman in a satin dress',featured:true,newArrival:true,materials:'100% recycled satin',sku:'VE-DR-002'},
  {id:'p3',name:'Relaxed Cotton Shirt',slug:'relaxed-cotton-shirt',category:'Shirts',gender:'Men',price:145,description:'An everyday essential in crisp organic cotton with a relaxed, generous fit.',colors:['White','Sky'],sizes:['S','M','L','XL'],image:img('photo-1617127365659-c47fa864d8bc'),imageAlt:'Man wearing a white shirt',newArrival:true,materials:'100% organic cotton',sku:'VE-SH-003'},
  {id:'p4',name:'Wide Leg Tailored Trouser',slug:'wide-leg-tailored-trouser',category:'Trousers',gender:'Women',price:210,description:'Precise tailoring and an elongated wide leg create an effortless uniform.',colors:['Charcoal','Stone'],sizes:['XS','S','M','L'],image:img('photo-1594633312681-425c7b97ccd1'),imageAlt:'Tailored trousers in a studio',featured:true,materials:'55% wool, 45% recycled polyester',sku:'VE-TR-004'},
  {id:'p5',name:'Merino Rib Knit',slug:'merino-rib-knit',category:'Essentials',gender:'Men',price:160,description:'A fine-gauge merino knit with a close, comfortable fit for layering.',colors:['Moss','Ink','Ecru'],sizes:['S','M','L','XL'],image:img('photo-1529139574466-a303027c1d8b'),imageAlt:'Model in a fine knit',newArrival:true,materials:'100% extrafine merino wool',sku:'VE-ES-005'},
  {id:'p6',name:'Leather Frame Bag',slug:'leather-frame-bag',category:'Accessories',gender:'Accessories',price:260,description:'A compact structured bag finished with a sculptural metal frame.',colors:['Black','Cognac'],sizes:['One size'],image:img('photo-1584917865442-de89df76afd3'),imageAlt:'Black leather frame bag',featured:true,materials:'Full-grain leather',sku:'VE-AC-006'},
  {id:'p7',name:'Soft Alpaca Scarf',slug:'soft-alpaca-scarf',category:'Accessories',gender:'Accessories',price:95,description:'A generous brushed scarf that brings warmth and quiet texture.',colors:['Oat','Moss'],sizes:['One size'],image:img('photo-1601924994987-69e26d50dc26'),imageAlt:'Neutral wool scarf',materials:'60% alpaca, 40% wool',sku:'VE-AC-007'},
  {id:'p8',name:'Everyday Leather Loafer',slug:'everyday-leather-loafer',category:'Accessories',gender:'Men',price:230,description:'A polished leather loafer with a softened square toe and low profile.',colors:['Black','Brown'],sizes:['40','41','42','43','44'],image:img('photo-1533867617858-e7b97e060509'),imageAlt:'Black leather loafers',featured:true,materials:'Leather upper and sole',sku:'VE-SH-008'},
  {id:'p9',name:'Pleated Utility Jacket',slug:'pleated-utility-jacket',category:'Outerwear',gender:'Women',price:310,compareAt:390,description:'A structured layer with utility pockets, relaxed shoulders and a fluid drape.',colors:['Khaki','Stone'],sizes:['XS','S','M','L'],image:img('photo-1529139574466-a303027c1d8b'),imageAlt:'Woman in utility jacket',featured:true,newArrival:true,materials:'Recycled cotton twill',sku:'VE-OW-009'},
  {id:'p10',name:'Pleated Slip Skirt',slug:'pleated-slip-skirt',category:'Dresses',gender:'Women',price:185,description:'A movement-rich skirt in a silky finish that sits lightly at the waist.',colors:['Ink','Sand'],sizes:['XS','S','M','L'],image:img('photo-1524504388940-b1c1722653e1'),imageAlt:'Model in a pleated skirt',newArrival:true,materials:'Silk blend',sku:'VE-DR-010'},
  {id:'p11',name:'Cashmere Crew Sweater',slug:'cashmere-crew-sweater',category:'Knitwear',gender:'Women',price:260,description:'A soft cashmere crew in a clean, polished silhouette with an easy drape.',colors:['Ivory','Moss','Charcoal'],sizes:['XS','S','M','L'],image:img('photo-1483985988355-763728e1935b'),imageAlt:'Cashmere crew sweater',featured:true,materials:'100% cashmere',sku:'VE-KN-011'},
  {id:'p12',name:'Oversized Wool Blazer',slug:'oversized-wool-blazer',category:'Outerwear',gender:'Men',price:340,compareAt:410,description:'Strong shoulders and a soft shoulder line create a confident, modern blazer.',colors:['Midnight','Ivory'],sizes:['S','M','L','XL'],image:img('photo-1517841905240-472988babdf9'),imageAlt:'Man in wool blazer',featured:true,materials:'Wool blend',sku:'VE-OW-012'},
  {id:'p13',name:'Recycled Cotton Tee',slug:'recycled-cotton-tee',category:'Essentials',gender:'Men',price:78,description:'A crisp everyday tee in recycled cotton with an easy, close fit.',colors:['White','Black','Forest'],sizes:['S','M','L','XL'],image:img('photo-1521572267360-ee0c2909d518'),imageAlt:'Plain tee',newArrival:true,materials:'100% recycled cotton',sku:'VE-ES-013'},
  {id:'p14',name:'Italian Wool Trousers',slug:'italian-wool-trousers',category:'Trousers',gender:'Men',price:220,description:'Italian wool weight and a tapering leg give these trousers structure without stiffness.',colors:['Charcoal','Olive'],sizes:['S','M','L','XL'],image:img('photo-1507679799987-c73779587ccf'),imageAlt:'Man wearing tailored trousers',featured:true,materials:'100% wool',sku:'VE-TR-014'},
  {id:'p15',name:'Shearling Leather Tote',slug:'shearling-leather-tote',category:'Accessories',gender:'Accessories',price:290,description:'A generous tote with softly finished shearling trim and a full-grain finish.',colors:['Camel','Black'],sizes:['One size'],image:img('photo-1542291026-7eec264c27ff'),imageAlt:'Leather tote on chair',featured:true,materials:'Leather and shearling',sku:'VE-AC-015'},
  {id:'p16',name:'Silk Poplin Shirt',slug:'silk-poplin-shirt',category:'Shirts',gender:'Women',price:170,description:'An airy poplin with silk content for a fluid feel and crisp finish.',colors:['Pearl','Rose'],sizes:['XS','S','M','L'],image:img('photo-1529139574466-a303027c1d8b'),imageAlt:'Woman in a silk shirt',materials:'65% silk, 35% cotton',sku:'VE-SH-016'},
  {id:'p17',name:'Oversized Knit Polo',slug:'oversized-knit-polo',category:'Knitwear',gender:'Men',price:180,description:'A knit polo with a softened collar and slightly roomier body.',colors:['Ivory','Moss'],sizes:['S','M','L','XL'],image:img('photo-1521572267360-ee0c2909d518'),imageAlt:'Man in knit polo',newArrival:true,materials:'Cotton blend knit',sku:'VE-KN-017'},
  {id:'p18',name:'Fleece Zip Hoodie',slug:'fleece-zip-hoodie',category:'Essentials',gender:'Men',price:150,description:'Warm fleece with a clean zip pocket and easy silhouette.',colors:['Graphite','Olive'],sizes:['S','M','L','XL'],image:img('photo-1524504388940-b1c1722653e1'),imageAlt:'Zip hoodie',materials:'70% cotton, 30% polyester',sku:'VE-ES-018'},
  {id:'p19',name:'Minimal Leather Belt',slug:'minimal-leather-belt',category:'Accessories',gender:'Accessories',price:110,description:'A slim leather belt finished in a brushed buckle for everyday wear.',colors:['Black','Tan'],sizes:['S','M','L'],image:img('photo-1523170335258-f5ed11844a49'),imageAlt:'Leather belt',materials:'Full-grain leather',sku:'VE-AC-019'},
  {id:'p20',name:'Structured Crossbody',slug:'structured-crossbody',category:'Accessories',gender:'Accessories',price:240,description:'A compact crossbody with strong lines, polished hardware and a refined silhouette.',colors:['Cocoa','Black'],sizes:['One size'],image:img('photo-1584917865442-de89df76afd3'),imageAlt:'Structured crossbody bag',featured:true,materials:'Pebbled vegan leather',sku:'VE-AC-020'},
  {id:'p21',name:'Satin Bias Midi',slug:'satin-bias-midi',category:'Dresses',gender:'Women',price:260,description:'Bias-cut satin that moves softly while skimming the body with ease.',colors:['Cinder','Blush'],sizes:['XS','S','M','L'],image:img('photo-1496747611176-843222e1e57c'),imageAlt:'Woman in satin midi dress',newArrival:true,materials:'100% satin',sku:'VE-DR-021'},
  {id:'p22',name:'Tailored Wool Blazer',slug:'tailored-wool-blazer',category:'Outerwear',gender:'Women',price:390,compareAt:470,description:'A refined blazer with a soft, architectural line for work and off-duty polish.',colors:['Black','Stone'],sizes:['XS','S','M','L'],image:img('photo-1524504388940-b1c1722653e1'),imageAlt:'Woman in wool blazer',featured:true,materials:'Wool and silk blend',sku:'VE-OW-022'},
  {id:'p23',name:'Soft Cotton Hoodie',slug:'soft-cotton-hoodie',category:'Essentials',gender:'Women',price:118,description:'A brushed cotton hoodie for easy layering with a softer drape.',colors:['Stone','Shell'],sizes:['XS','S','M','L'],image:img('photo-1521572267360-ee0c2909d518'),imageAlt:'Woman in cotton hoodie',materials:'100% cotton',sku:'VE-ES-023'},
  {id:'p24',name:'Linen Drawstring Trousers',slug:'linen-drawstring-trousers',category:'Trousers',gender:'Women',price:180,description:'Breathable linen with a light drawstring waist for a relaxed shape.',colors:['Natural','Oat'],sizes:['XS','S','M','L'],image:img('photo-1529139574466-a303027c1d8b'),imageAlt:'Woman wearing linen trousers',materials:'100% linen',sku:'VE-TR-024'},
  {id:'p25',name:'Cashmere V-Neck',slug:'cashmere-v-neck',category:'Knitwear',gender:'Men',price:220,description:'A refined cashmere v-neck that layers effortlessly over shirting.',colors:['Mocha','Cream'],sizes:['S','M','L','XL'],image:img('photo-1515886657613-9f3515b0c78f'),imageAlt:'Man in cashmere v-neck',featured:true,materials:'100% cashmere',sku:'VE-KN-025'},
  {id:'p26',name:'Contrast Trim Trench',slug:'contrast-trim-trench',category:'Outerwear',gender:'Men',price:360,description:'A classic trench with tonal contrast and a slightly relaxed silhouette.',colors:['Stone','Black'],sizes:['S','M','L','XL'],image:img('photo-1507679799987-c73779587ccf'),imageAlt:'Man in trench coat',newArrival:true,materials:'Cotton and nylon',sku:'VE-OW-026'},
  {id:'p27',name:'Drape Front Slip Dress',slug:'drape-front-slip-dress',category:'Dresses',gender:'Women',price:240,description:'A soft drape front creates a fluid, feminine line with a minimal finish.',colors:['Mink','Black'],sizes:['XS','S','M','L'],image:img('photo-1487412720507-e7ab37603c6f'),imageAlt:'Woman in drape slip dress',featured:true,materials:'Recycled satin',sku:'VE-DR-027'},
  {id:'p28',name:'Check Wool Overshirt',slug:'check-wool-overshirt',category:'Outerwear',gender:'Men',price:185,description:'A structured overshirt with a check finish built for daily layering.',colors:['Forest','Brick'],sizes:['S','M','L','XL'],image:img('photo-1483985988355-763728e1935b'),imageAlt:'Man in checked overshirt',materials:'Wool blend',sku:'VE-OW-028'},
  {id:'p29',name:'Merino Crew Neck',slug:'merino-crew-neck',category:'Knitwear',gender:'Women',price:170,description:'An easy merino crew that sits softly against the skin and layers neatly.',colors:['Oat','Forest'],sizes:['XS','S','M','L'],image:img('photo-1487412720507-e7ab37603c6f'),imageAlt:'Woman in merino crew neck',materials:'100% merino wool',sku:'VE-KN-029'},
  {id:'p30',name:'Leather Mules',slug:'leather-mules',category:'Accessories',gender:'Accessories',price:210,description:'A minimal mule with sculpted sole and soft leather finish.',colors:['Black','Taupe'],sizes:['36','37','38','39','40'],image:img('photo-1543163521-1bf539c55dd2'),imageAlt:'Leather mules',featured:true,materials:'Leather',sku:'VE-AC-030'},
  {id:'p31',name:'Textured Leather Backpack',slug:'textured-leather-backpack',category:'Accessories',gender:'Accessories',price:280,description:'A versatile everyday backpack finished in textured leather and brushed hardware.',colors:['Cognac','Black'],sizes:['One size'],image:img('photo-1525966222134-fcfa99b8ae77'),imageAlt:'Leather backpack',materials:'Leather and cotton lining',sku:'VE-AC-031'},
  {id:'p32',name:'Pleated Wool Skirt',slug:'pleated-wool-skirt',category:'Trousers',gender:'Women',price:210,description:'A softly pleated wool skirt with structure and a clean line through the hip.',colors:['Graphite','Oat'],sizes:['XS','S','M','L'],image:img('photo-1515886657613-9f3515b0c78f'),imageAlt:'Woman in pleated wool skirt',materials:'Wool blend',sku:'VE-TR-032'},
  {id:'p33',name:'Oversized Button Shirt',slug:'oversized-button-shirt',category:'Shirts',gender:'Women',price:155,description:'A generous buttoned shirt with a laid-back collar and easy shape.',colors:['White','Sky'],sizes:['XS','S','M','L'],image:img('photo-1496747611176-843222e1e57c'),imageAlt:'Woman in button shirt',newArrival:true,materials:'Cotton poplin',sku:'VE-SH-033'},
  {id:'p34',name:'Tech Wool Trouser',slug:'tech-wool-trouser',category:'Trousers',gender:'Men',price:200,description:'A technical wool trouser with comfortable stretch and sharp drape.',colors:['Ink','Moss'],sizes:['S','M','L','XL'],image:img('photo-1521572267360-ee0c2909d518'),imageAlt:'Tech wool trouser',materials:'65% wool, 35% stretch nylon',sku:'VE-TR-034'},
  {id:'p35',name:'Double-Face Coat',slug:'double-face-coat',category:'Outerwear',gender:'Women',price:410,description:'A double-faced wool coat with a sculpted shape and enduring warmth.',colors:['Stone','Black'],sizes:['XS','S','M','L'],image:img('photo-1524504388940-b1c1722653e1'),imageAlt:'Double-face coat',featured:true,materials:'Double-faced wool',sku:'VE-OW-035'},
  {id:'p36',name:'Poplin Pleat Dress',slug:'poplin-pleat-dress',category:'Dresses',gender:'Women',price:220,description:'A crisp dress with a gently pleated skirt for an elevated everyday finish.',colors:['Ivory','Sky'],sizes:['XS','S','M','L'],image:img('photo-1483985988355-763728e1935b'),imageAlt:'Woman in poplin dress',materials:'100% cotton poplin',sku:'VE-DR-036'},
  {id:'p37',name:'Ribbed Tank',slug:'ribbed-tank',category:'Essentials',gender:'Women',price:72,description:'A close ribbed tank made for layering or wearing solo in warm weather.',colors:['Bone','Black','Peony'],sizes:['XS','S','M','L'],image:img('photo-1517841905240-472988babdf9'),imageAlt:'Woman in ribbed tank',materials:'Organic cotton jersey',sku:'VE-ES-037'},
  {id:'p38',name:'Cotton Twill Cargo',slug:'cotton-twill-cargo',category:'Trousers',gender:'Men',price:170,description:'A utility cargo with a clean profile and softly tapered leg.',colors:['Olive','Stone'],sizes:['S','M','L','XL'],image:img('photo-1539109136881-3be0616acf4b'),imageAlt:'Cargo trousers',materials:'100% cotton twill',sku:'VE-TR-038'},
  {id:'p39',name:'Leather Weekender',slug:'leather-weekender',category:'Accessories',gender:'Accessories',price:310,description:'A weekend-ready leather case with a roomy interior and polished hardware.',colors:['Black','Oak'],sizes:['One size'],image:img('photo-1525966222134-fcfa99b8ae77'),imageAlt:'Leather weekender',featured:true,materials:'Full-grain leather',sku:'VE-AC-039'},
  {id:'p40',name:'Brushed Flannel Shirt',slug:'brushed-flannel-shirt',category:'Shirts',gender:'Men',price:160,description:'A brushed flannel shirt with a soft hand feel and classic collar shape.',colors:['Cinder','Moss'],sizes:['S','M','L','XL'],image:img('photo-1496747611176-843222e1e57c'),imageAlt:'Man in flannel shirt',materials:'Cotton flannel',sku:'VE-SH-040'},
  {id:'p41',name:'Heritage Crew Sweatshirt',slug:'heritage-crew-sweatshirt',category:'Essentials',gender:'Men',price:140,description:'An elevated crew sweatshirt with a premium weight and soft face.',colors:['Sand','Black'],sizes:['S','M','L','XL'],image:img('photo-1524504388940-b1c1722653e1'),imageAlt:'Crew sweatshirt',newArrival:true,materials:'80% cotton, 20% wool',sku:'VE-ES-041'},
  {id:'p42',name:'Wool Blend Trouser',slug:'wool-blend-trouser',category:'Trousers',gender:'Women',price:240,description:'A structured wool-blend trouser cut with a gentle taper and fluid drop.',colors:['Ink','Stone'],sizes:['XS','S','M','L'],image:img('photo-1594633312681-425c7b97ccd1'),imageAlt:'Wool blend trouser',materials:'Wool blend',sku:'VE-TR-042'},
  {id:'p43',name:'Satin Wrap Top',slug:'satin-wrap-top',category:'Essentials',gender:'Women',price:165,description:'An easy satin wrap top designed for layering with a soft, fluid feel.',colors:['Rose','Black'],sizes:['XS','S','M','L'],image:img('photo-1487412720507-e7ab37603c6f'),imageAlt:'Satin wrap top',materials:'Satin finish fabric',sku:'VE-ES-043'},
  {id:'p44',name:'Canvas Tote',slug:'canvas-tote',category:'Accessories',gender:'Accessories',price:92,description:'A classic canvas tote for everyday use, finished with a clean stitched handle.',colors:['Natural','Storm'],sizes:['One size'],image:img('photo-1542291026-7eec264c27ff'),imageAlt:'Canvas tote bag',materials:'Cotton canvas',sku:'VE-AC-044'},
  {id:'p45',name:'Everyday Denim',slug:'everyday-denim',category:'Essentials',gender:'Men',price:190,description:'A modern straight jean with a slightly roomier fit and soft wash.',colors:['Indigo','Washed Blue'],sizes:['S','M','L','XL'],image:img('photo-1541099649105-f69ad21f3246'),imageAlt:'Men in denim',newArrival:true,materials:'98% cotton, 2% elastane',sku:'VE-ES-045'},
  {id:'p46',name:'Padded Bomber',slug:'padded-bomber',category:'Outerwear',gender:'Men',price:300,description:'A lightweight bomber with a soft padded interior and clean collar.',colors:['Forest','Black'],sizes:['S','M','L','XL'],image:img('photo-1523170335258-f5ed11844a49'),imageAlt:'Padded bomber',featured:true,materials:'Polyester shell',sku:'VE-OW-046'},
  {id:'p47',name:'Mohair Cardigan',slug:'mohair-cardigan',category:'Knitwear',gender:'Women',price:220,description:'An airy mohair cardigan with texture, softness and generous drape.',colors:['Cream','Putty'],sizes:['XS','S','M','L'],image:img('photo-1483985988355-763728e1935b'),imageAlt:'Woman in cardigan',featured:true,materials:'Mohair blend',sku:'VE-KN-047'},
  {id:'p48',name:'Leather Travel Tote',slug:'leather-travel-tote',category:'Accessories',gender:'Accessories',price:330,description:'A structured travel tote with a polished interior and thoughtful organization.',colors:['Black','Cocoa'],sizes:['One size'],image:img('photo-1543163521-1bf539c55dd2'),imageAlt:'Leather travel tote',materials:'Full-grain leather',sku:'VE-AC-048'},
  {id:'p49',name:'Soft Knit Polo',slug:'soft-knit-polo',category:'Knitwear',gender:'Men',price:165,description:'A smooth knit polo that balances a classic collar with a soft body.',colors:['Ivory','Ink'],sizes:['S','M','L','XL'],image:img('photo-1521572267360-ee0c2909d518'),imageAlt:'Man in knit polo',materials:'Cotton knit',sku:'VE-KN-049'},
  {id:'p50',name:'Minimal Camera Bag',slug:'minimal-camera-bag',category:'Accessories',gender:'Accessories',price:205,description:'A compact camera bag with a structured profile and quietly modern hardware.',colors:['Black','Sand'],sizes:['One size'],image:img('photo-1584917865442-de89df76afd3'),imageAlt:'Minimal camera bag',materials:'Pebbled vegan leather',sku:'VE-AC-050'},
];

export function getProduct(slug: string) {
  return products.find((product) => product.slug === slug);
}

export function getProducts(params?: { q?: string; category?: string; gender?: string; sort?: string }) {
  let result = [...products];

  if (params?.q) {
    const q = params.q.toLowerCase();
    result = result.filter((p) => `${p.name} ${p.category} ${p.description}`.toLowerCase().includes(q));
  }

  if (params?.category) {
    result = result.filter((p) => p.category.toLowerCase() === params.category?.toLowerCase());
  }

  if (params?.gender) {
    result = result.filter((p) => p.gender.toLowerCase() === params.gender?.toLowerCase());
  }

  if (params?.sort === 'price-low') result.sort((a, b) => a.price - b.price);
  if (params?.sort === 'price-high') result.sort((a, b) => b.price - a.price);
  if (params?.sort === 'newest') result = result.filter((p) => p.newArrival);

  return result;
}

